### ISSUE TITLE
question: what are the columns in the DAT file

### ISSUE THREAD

**Issue by alexlib** [lento234/pivuq#40]
https://github.com/lento234/pivuq/blob/main/examples/data/particledisparity_code_testdata/B00010_UQ.dat 

what are the columns and how they've obtained? I'd like to create a similar set using openpiv-python. 

Thanks

**Comment by lento234** [comment]
Hi @alexlib 

I obtained the dataset from the `PIV Particle Disparity Code` from http://piv.de/uncertainty/?page_id=221. It is the Uncertainty data from the folder `Uncertainty`.

The columns are positions, PIV vectors, disparities and number of particles in the grid for disparity analysis. More explicitly:
 * `x`: x-position
 * `y`: y-position
 * `u`: u component
 * `v`: v component
 * `ex`: disparity error, x-component
 * `ey`: disparity error, y-component
 * `N`:  Number of particles inside the grid identified in disparity calculation 

The output grid is the same as the initial PIV vector analysis (`i=128`, `j=128`). However, I think the coordinates are different because of the re-gridding and interpolation. 

As of now, in my code, I have done this sub-sampling to the PIV grid. I have done a UQ at a pixel-level. I will need to add the down sampling element as the last step in the analysis. 

Best,
Lento

**Comment by alexlib** [comment]
So we need to add to `openpiv-python` the code that generates the total disparity errors, right?

**Comment by alexlib** [comment]
I got it @lento234 - this is a sort of ground truth data that you can compare to using your algorithm. `openpiv` has to generate from those images the same `x,y,u,v` and then your code generates `ex, ey, N` and then we can compare it to the ground truth. Since you already did the test of the disparity, the remaining part for `openpiv` is to generate the vector fields at the same locations using the same images.

**Comment by lento234** [comment]
Yes, exactly.
